spring.application.name=course_app
spring.data.rest.base-path=/api

# Database connection settings
spring.datasource.url=jdbc:sqlserver://java-course-app-sql-server.database.windows.net:1433;database=java-course-app-sql-database;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=billy@java-course-app-sql-server
spring.datasource.password=Password1

# JPA/Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Connection pooling settings (optional, for Tomcat pool)
spring.datasource.tomcat.max-wait=30000
spring.datasource.tomcat.max-active=20
spring.datasource.tomcat.initial-size=5

# JPA and Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
